
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 21 13:50:04 COT 2016
//----------------------------------------------------

package main;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CADENA = 14;
  public static final int MINUS = 3;
  public static final int INT = 13;
  public static final int DIVIDE = 5;
  public static final int A_ENTERO = 11;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int ASIG = 10;
  public static final int ID = 15;
  public static final int error = 1;
  public static final int RPAREN = 9;
  public static final int PRINT = 7;
  public static final int TIMES = 4;
  public static final int PUNTOYCOMA = 6;
  public static final int A_CADENA = 12;
  public static final int LPAREN = 8;
}

